# FILL IN THE MISSING VALUES BELOW
alerting:
  github:
    token: "<github-token>" # WARN: DO NOT CHANGE THIS LINE
# FILL IN THE MISSING VALUES ABOVE

# FILL IN THE MISSING VALUES BELOW
endpoints:
  - name: Leantime
    url: <leantime-url> # WARN: DO NOT CHANGE THIS LINE
    interval:
    conditions:
    alerts:
      - type: github
        description: "Sensei, Leantime is down! Please check and fix it."

  - name: Gatus
    url: <gatus-url> # WARN: DO NOT CHANGE THIS LINE
    interval:
    conditions:
    alerts:
      - type: github
        description: "Sensei, Gatus is down! Please check and fix it."
# FILL IN THE MISSING VALUES BELOW
